package com.solutions.app.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF004DA4)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0070EA)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF405E96)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB1C9FF)
val onSecondaryContainerLight = Color(0xFF14376C)
val tertiaryLight = Color(0xFF004493)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF0067D7)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF181C23)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF181C23)
val surfaceVariantLight = Color(0xFFDDE2F4)
val onSurfaceVariantLight = Color(0xFF414754)
val outlineLight = Color(0xFF717786)
val outlineVariantLight = Color(0xFFC1C6D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3039)
val inverseOnSurfaceLight = Color(0xFFEEF0FB)
val inversePrimaryLight = Color(0xFFADC7FF)
val surfaceDimLight = Color(0xFFD7D9E5)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F3FE)
val surfaceContainerLight = Color(0xFFEBEDF9)
val surfaceContainerHighLight = Color(0xFFE6E8F3)
val surfaceContainerHighestLight = Color(0xFFE0E2ED)

val primaryDark = Color(0xFFADC7FF)
val onPrimaryDark = Color(0xFF002E68)
val primaryContainerDark = Color(0xFF0070EA)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFADC7FF)
val onSecondaryDark = Color(0xFF072F64)
val secondaryContainerDark = Color(0xFF1E3F74)
val onSecondaryContainerDark = Color(0xFFC2D5FF)
val tertiaryDark = Color(0xFFACC7FF)
val onTertiaryDark = Color(0xFF002E68)
val tertiaryContainerDark = Color(0xFF005EC5)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10131B)
val onBackgroundDark = Color(0xFFE0E2ED)
val surfaceDark = Color(0xFF10131B)
val onSurfaceDark = Color(0xFFE0E2ED)
val surfaceVariantDark = Color(0xFF414754)
val onSurfaceVariantDark = Color(0xFFC1C6D7)
val outlineDark = Color(0xFF8B90A0)
val outlineVariantDark = Color(0xFF414754)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2ED)
val inverseOnSurfaceDark = Color(0xFF2D3039)
val inversePrimaryDark = Color(0xFF005BC0)
val surfaceDimDark = Color(0xFF10131B)
val surfaceBrightDark = Color(0xFF363942)
val surfaceContainerLowestDark = Color(0xFF0B0E16)
val surfaceContainerLowDark = Color(0xFF181C23)
val surfaceContainerDark = Color(0xFF1C2027)
val surfaceContainerHighDark = Color(0xFF272A32)
val surfaceContainerHighestDark = Color(0xFF31353D)






